# Default values for ArgoCD demo Helm chart
# Can be overridden during helm install/upgrade

namespace: k8s-minimal
replicaCount: 2

image:
  repository: oren1984/k8s-argocd-lab
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

ingress:
  enabled: false
  className: nginx
  host: argocd-demo.local
